FROM nginx:alpine

LABEL maintainer="Ankit Bhange"
LABEL description="Ankit's Neon Snake Game"

RUN apk add --no-cache curl net-tools jq

COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]