FROM nginx:alpine

LABEL maintainer="Ankit Bhange"
LABEL description="Ankit's Neon Snake Game"

COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY script.js /usr/share/nginx/html/script.js

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]